<% require "uri" %>

db_config: &db_config
  <% if ENV["DATABASE_URL"].present? %>
  <% uri = URI.parse(ENV["DATABASE_URL"]) if ENV["DATABASE_URL"].present? %>
  username: <%= uri.user %>
  password: <%= uri.password %>
  host:     <%= uri.host %>
  <% else %>
  username: root
  password: ''
  host: localhost
  <% end %>
  adapter: mysql2
  pool: 10
  timeout: 5000
  port: 3306

development:
  <<: *db_config
  database: APPNAME_development

test:
  <<: *db_config
  database: APPNAME_test

staging:
  <<: *db_config
  database: APPNAME_staging

production:
  <<: *db_config
  database: APPNAME_production
